# Numpy

NumPy is the fundamental package for scientific computing with Python.
 Its main feature is the powerful N-dimensional array object.

`pip install numpy`

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
list1 = [1, 2, 3, 4]
a = np.array(list1)
print(a)
print(type(a)) # The type is ndarray (N-dimensional array)

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
print("Dimensions:", a.ndim)  # Number of dimensions
print("Data type:", a.dtype)  # The data type of the elements

Dimensions: 1
Data type: int64


### Creating Special Arrays

In [5]:
a = np.ones((2, 3)) # Create an array of all ones with shape (2, 3)
print(a)

a = np.zeros((2, 3)) # Create an array of all zeros
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


 `arange` is like Python's `range` but returns a NumPy array.

In [6]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


### Operations on NumPy Arrays

In [7]:
a = np.array([[10, 20, 30], [40, 50, 60]])
print(a.sum()) # Sum of all elements
print(np.power(a, 3)) # Raise every element to the power of 3

210
[[  1000   8000  27000]
 [ 64000 125000 216000]]


Vectorized operations are much faster than looping in Python.

In [8]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
c = a - b # Subtracts elements at the same position
print(c)
d = a * b # Multiplies elements at the same position
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


### Shape and Reshaping

 The shape is a tuple representing the size of the array in each dimension.


In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print("Shape:", arr.shape)

Shape: (1, 1, 1, 1, 4)


In [10]:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])

 Reshape changes the shape of the array without changing its data.
 The total number of elements must remain the same.
 -1 tells NumPy to automatically calculate the size of that dimension.

In [11]:
newarr = arr.reshape(2, -1)
print(newarr)

[[1 2 3 4 1 2]
 [3 4 1 2 3 4]]


### Random Numbers

In [12]:
x = np.random.rand(2, 2, 3, 4)
print("\nRandom array shape:", x.shape)


Random array shape: (2, 2, 3, 4)


### Boolean Indexing

In [13]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [14]:
print(a > 2)

[False False False  True  True  True]


In [15]:
print((a > 2) & (a < 4))

[False False False  True False False]


### Copy vs. View

This is a critical concept in NumPy for memory management.

In [16]:
print("\n--- Copy Example ---")
arr = np.array([1, 2, 3, 4])
x = arr.copy()
arr[0] = -50 # Change the original
print("Original:", arr)
print("Copy:", x) # The copy is not affected


--- Copy Example ---
Original: [-50   2   3   4]
Copy: [1 2 3 4]


In [17]:
print("\n--- View Example ---")
arr = np.array([1, 2, 3, 4])
x = arr.view()
arr[0] = -50 # Change the original
print("Original:", arr)
print("View:", x) # The view is also changed


--- View Example ---
Original: [-50   2   3   4]
View: [-50   2   3   4]


### NumPy vs. Python List Performance

This section demonstrates the significant speed advantage of NumPy for
 numerical calculations on large datasets.

In [18]:
print("\n--- NumPy vs. Python List Performance ---")
# Re-importing time and random in case the script is run in sections
import time
import random

size = 10000000
python_list = [random.random() for _ in range(size)]
numpy_array = np.array(python_list)

def time_op(operation, name):
    start_time = time.time()
    operation()
    elapsed_time = time.time() - start_time
    print(f"{name}: {elapsed_time:.6f} seconds")
    return elapsed_time

print("\nSum of Elements")
list_time = time_op(lambda: sum(python_list), "Python List Sum")
array_time = time_op(lambda: np.sum(numpy_array), "NumPy Array Sum")
print(f"NumPy is {list_time/array_time:.2f}x faster" if array_time > 0 else "NumPy is infinitely faster")

print("\nFinding Maximum Value")
list_time = time_op(lambda: max(python_list), "Python List Max")
array_time = time_op(lambda: np.max(numpy_array), "NumPy Array Max")
print(f"NumPy is {list_time/array_time:.2f}x faster" if array_time > 0 else "NumPy is infinitely faster")


--- NumPy vs. Python List Performance ---

Sum of Elements
Python List Sum: 0.073521 seconds
NumPy Array Sum: 0.006906 seconds
NumPy is 10.65x faster

Finding Maximum Value
Python List Max: 0.120523 seconds
NumPy Array Max: 0.004440 seconds
NumPy is 27.15x faster
