# Pandas

Pandas is built on top of NumPy, which is a library for working with large, multi-dimensional arrays and matrices. Pandas extends the capabilities of NumPy by providing a more flexible and feature-rich data structure called the DataFrame, which allows for the efficient manipulation and analysis of tabular data.

In [2]:
!pip install pandas

In [3]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.2.2
2.0.2


- Series: A one-dimensional labeled array that can hold any data type, similar to a column in a spreadsheet or a SQL table.
- DataFrame: A two-dimensional labeled data structure with columns of potentially different data types, similar to a table in a spreadsheet or a SQL database.

In [4]:
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'city': ['New York', 'London', 'Paris']
}
df = pd.DataFrame(data)
df

name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [5]:
df['name']

0      Alice
1        Bob
2    Charlie
Name: name, dtype: object

In [6]:
df.iloc[1]

name       Bob
age         30
city    London
Name: 1, dtype: object

In [7]:
df['age'].dtype

dtype('int64')

# Series

- **Homogeneous Data:** All elements in a Series must be of the same data type. If you attempt to create a Series with mixed data types, Pandas will automatically upcast the data to the most compatible data type.

- **Mutable:** Series objects are mutable, meaning you can change, add, or delete elements after creation.

- **Size Immutable:** While the contents of a Series can be modified, the size of a Series is fixed upon creation. To change the size, you need to create a new Series object.

- **Labeled Index:** Each element in a Series is associated with a unique label called an index. The index can be integer-based (default) or can consist of user-defined labels (e.g., strings, dates, or other hashable objects).

### Creating a Series

In [8]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
data = np.array([1, 2, 3, 4, 5])
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

The keys of the dictionary become the index labels, and the values become the Series values.

In [10]:
data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
series = pd.Series(data)
series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index, name='example', dtype='float64')
series

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: example, dtype: float64

### Series Attributes

In [12]:
print(series.dtype)
print(series.shape)
print(series.size)
print(series.index)
print(series.values)

float64
(5,)
5
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[1. 2. 3. 4. 5.]


### Vectorized Operations

In [13]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)

In [14]:
series + 2

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [15]:
series ** 2

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [16]:
np.log(series)

0    0.000000
1    0.693147
2    1.098612
3    1.386294
4    1.609438
dtype: float64

In [17]:
series > 2

0    False
1    False
2     True
3     True
4     True
dtype: bool

### Label Alignment

In [18]:
series1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
series2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])

series1 + series2

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64

### Series Methods

In [19]:
data = [1, 1, 1, 2, 2, 2, 2, 3, 4, 4, 4, 5, 6]
series = pd.Series(data)

In [20]:
print(series.unique())
print(series.value_counts())

[1 2 3 4 5 6]
2    4
1    3
4    3
3    1
5    1
6    1
Name: count, dtype: int64


In [21]:
data = [4, 2, 8, 1, 9, 5]
series = pd.Series(data)

series.sort_values()

3    1
1    2
0    4
5    5
2    8
4    9
dtype: int64

In [22]:
data = [4, 2, 8, 1, 9, 5]
index = ['b', 'd', 'a', 'e', 'c', 'f']
series = pd.Series(data, index=index)

series.sort_index()

a    8
b    4
c    9
d    2
e    1
f    5
dtype: int64

### Converting to Datetime

In [23]:
dates = pd.Series(['2024-01-01', '2024-02-15', 'July, 30, 2024'])
pd.to_datetime(dates, format='mixed')

0   2024-01-01
1   2024-02-15
2   2024-07-30
dtype: datetime64[ns]

# DataFrames
A DataFrame is a two-dimensional labeled data structure with columns of potentially different types. You can think of it as a spreadsheet or a SQL table, where data is organized in rows and columns. Each column in a DataFrame is a Pandas Series, which means that a DataFrame can be thought of as a collection of Series objects that share the same index.

In [65]:
from sklearn.datasets import load_iris

iris = load_iris()

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

### Creating DataFrames

In [24]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

In [25]:
pd.DataFrame(d)

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [26]:
pd.DataFrame(d, index=['b','c','d'], columns=["one","two","three"])

one  two three
b  2.0  2.0   NaN
c  3.0  3.0   NaN
d  NaN  4.0   NaN

### DataFrame Attributes

In [27]:
df = pd.DataFrame({"A": range(1,6), "B": range(6,11), "C": range(11,16), "D":range(16,21)})

In [28]:
df

A   B   C   D
0  1   6  11  16
1  2   7  12  17
2  3   8  13  18
3  4   9  14  19
4  5  10  15  20

In [29]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)
print(df.values)

(5, 4)
Index(['A', 'B', 'C', 'D'], dtype='object')
RangeIndex(start=0, stop=5, step=1)
A    int64
B    int64
C    int64
D    int64
dtype: object
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
dtypes: int64(4)
memory usage: 292.0 bytes


In [31]:
df.describe()

A          B          C          D
count  5.000000   5.000000   5.000000   5.000000
mean   3.000000   8.000000  13.000000  18.000000
std    1.581139   1.581139   1.581139   1.581139
min    1.000000   6.000000  11.000000  16.000000
25%    2.000000   7.000000  12.000000  17.000000
50%    3.000000   8.000000  13.000000  18.000000
75%    4.000000   9.000000  14.000000  19.000000
max    5.000000  10.000000  15.000000  20.000000

In [32]:
df.head(2)

A  B   C   D
0  1  6  11  16
1  2  7  12  17

In [33]:
df.tail(2)

A   B   C   D
3  4   9  14  19
4  5  10  15  20

In [34]:
df1 = pd.DataFrame(np.random.randn(10, 7), columns=['A','B','C','D','E','F','G'])
df2 = pd.DataFrame(np.random.randn(8, 6), columns=['A','B','E','F','G','H'])

In [35]:
df1 + df2

A         B   C   D         E         F         G   H
0  0.125838 -1.005511 NaN NaN  0.296785  5.805871 -0.977424 NaN
1  0.008902  2.581609 NaN NaN  0.385339 -0.425776 -0.789537 NaN
2 -0.782929 -0.712146 NaN NaN -1.695627 -0.281202 -1.609973 NaN
3  0.182313  1.207899 NaN NaN -0.910071 -0.106560  0.884954 NaN
4  1.650457  1.315302 NaN NaN  1.409000  0.055779 -0.712764 NaN
5 -2.914354  2.047058 NaN NaN -0.601659  0.731928 -0.020598 NaN
6 -2.044331  0.594942 NaN NaN  1.531319 -0.327405  1.265269 NaN
7 -1.291744 -0.031656 NaN NaN  1.204947 -1.070008  1.187331 NaN
8       NaN       NaN NaN NaN       NaN       NaN       NaN NaN
9       NaN       NaN NaN NaN       NaN       NaN       NaN NaN

In [36]:
df1 = pd.DataFrame({"A": [True, False, True], "B": [False, True, True]})
df2 = pd.DataFrame({"A": [False, True, True], "B": [True, True, False]})

df1 & df2

A      B
0  False  False
1  False   True
2   True  False

### Selecting Columns in a DataFrame

In [37]:
df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8], 'C': [9, 10, 11, 12]}, index=['a', 'b', 'c', 'd'])
df

A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12

In [46]:
df[['A', 'B']]

A  B
a  1  5
b  2  6
c  3  7
d  4  8

In [47]:
df.loc['a':'c']

A  B   C
a  1  5   9
b  2  6  10
c  3  7  11

In [48]:
df.loc[:, 'A':'C']

A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12

In [50]:
df.loc[:, 'A':'C']

A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12

In [53]:
df.iloc[0:3] #exclusive

A  B   C
a  1  5   9
b  2  6  10
c  3  7  11

In [54]:
df.iloc[:, 0:2] #exclusive

A  B
a  1  5
b  2  6
c  3  7
d  4  8

In [55]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=['a', 'b', 'c'])
df

A  B
a  1  4
b  2  5
c  3  6

In [57]:
df.at['b', 'A']=4

### Query

In [60]:
df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [10, 20, 30, 40, 50], 'C': ['a', 'b', 'c', 'd', 'e']})
df.query('A > 2')

A   B  C
2  3  30  c
3  4  40  d
4  5  50  e

In [61]:
df.query('A > 2 & B < 40')

A   B  C
2  3  30  c

In [62]:
df.query('A < B & C == "d"')

A   B  C
3  4  40  d

In [63]:
df.query('A ** 2 > 10')

A   B  C
3  4  40  d
4  5  50  e

In [64]:
df.query('C.str.startswith("b")')

A   B  C
1  2  20  b

### Duplication

In [66]:
df2 = pd.DataFrame({
    'Name': ['John', 'Jane', 'John', 'Mike', 'Jane'],
    'Age': [28, 32, 28, 45, 33],
    'City': ['New York', 'Boston', 'Chicago', 'Chicago', 'Boston']
})

In [67]:
df2.duplicated(subset=['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

#### Removing duplicate data

In [69]:
df.drop_duplicates()

A   B  C
0  1  10  a
1  2  20  b
2  3  30  c
3  4  40  d
4  5  50  e

In [70]:
df = pd.DataFrame({
    'Name': ['John', 'Jane', 'John', 'Mike', 'Jane'],
    'Age': [28, 32, 28, 45, 33],
    'City': ['New York', 'Boston', 'Chicago', 'Chicago', 'Boston']
})
df

Name  Age      City
0  John   28  New York
1  Jane   32    Boston
2  John   28   Chicago
3  Mike   45   Chicago
4  Jane   33    Boston

In [71]:
df.drop_duplicates(subset=['Name'])

Name  Age      City
0  John   28  New York
1  Jane   32    Boston
3  Mike   45   Chicago

### Missing Values

In [93]:
df = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [5, np.nan, np.nan, 3, 2],
    'C': [1, 2, 3, np.nan, 5],
})

In [94]:
df

A    B    C
0  1.0  5.0  1.0
1  2.0  NaN  2.0
2  NaN  NaN  3.0
3  4.0  3.0  NaN
4  5.0  2.0  5.0

In [95]:
df.isnull()

A      B      C
0  False  False  False
1  False   True  False
2   True   True  False
3  False  False   True
4  False  False  False

In [96]:
df.isnull().any().any()

np.True_

In [97]:
df.isnull().sum()

A    1
B    2
C    1
dtype: int64

#### Handling missing values

In [98]:
s =pd.Series([1,2,np.nan,4, 5, np.nan])

In [99]:
s

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [100]:
s.dropna()

0    1.0
1    2.0
3    4.0
4    5.0
dtype: float64

In [101]:
df.fillna(0)

A    B    C
0  1.0  5.0  1.0
1  2.0  0.0  2.0
2  0.0  0.0  3.0
3  4.0  3.0  0.0
4  5.0  2.0  5.0

In [102]:
df.fillna({'A':0,'B':5, 'C':10})

A    B     C
0  1.0  5.0   1.0
1  2.0  5.0   2.0
2  0.0  5.0   3.0
3  4.0  3.0  10.0
4  5.0  2.0   5.0

In [103]:
df.ffill()

A    B    C
0  1.0  5.0  1.0
1  2.0  5.0  2.0
2  2.0  5.0  3.0
3  4.0  3.0  3.0
4  5.0  2.0  5.0

In [104]:
df.bfill()

A    B    C
0  1.0  5.0  1.0
1  2.0  3.0  2.0
2  4.0  3.0  3.0
3  4.0  3.0  5.0
4  5.0  2.0  5.0

Fill with mean of each column

In [105]:
df.fillna(df.mean())

A         B     C
0  1.0  5.000000  1.00
1  2.0  3.333333  2.00
2  3.0  3.333333  3.00
3  4.0  3.000000  2.75
4  5.0  2.000000  5.00

In [106]:
df.fillna(df.median())

A    B    C
0  1.0  5.0  1.0
1  2.0  3.0  2.0
2  3.0  3.0  3.0
3  4.0  3.0  2.5
4  5.0  2.0  5.0

#### Using replace() for Custom Missing Value Handling

In [107]:
df = pd.DataFrame({
    'A': [1, 2, -999, 4, 5],
    'B': ['a', 'N/A', 'c', 'Missing', 'e']
})

In [108]:
df.replace([-999, 'N/A', 'Missing'], np.nan)

A    B
0  1.0    a
1  2.0  NaN
2  NaN    c
3  4.0  NaN
4  5.0    e